name: Detect Secrets

on:
  push:
  pull_request:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Run detect-secrets against baseline
        run: |
          detect-secrets scan --baseline .secrets.baseline
