name: Dependency Track SBOM Upload

on: [push, pull_request]

jobs:
  dt_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Generate and Upload SBOM to Dependency‑Track
        id: dtUpload
        uses: Quobis/action-owasp-dependecy-track-check@main
        with:
          url: 'http://localhost:8081/dashboard'
          key: 'odt_p67g6Bwf_47fzhTIqsvnIm2RTCHmKkZIYs5N6wRVG'
          language: 'python'  # change based on your project language
          
      - name: Print Risk Score
        run: echo "Risk Score: ${{ steps.dtUpload.outputs.riskscore }}"
