name: Dependency Track Upload

on:
  push:
    branches: [main]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0.14.3
        with:
          output-file: sbom.json
          format: cyclonedx-json

      - name: Upload SBOM to Dependency-Track
        uses: Quobis/action-owasp-dependency-track-check@main
        with:
          apiKey: odt_p67g6Bwf_47fzhTIqsvnIm2RTCHmKkZIYs5N6wRVG
          serverUrl: http://localhost:8081
          projectName: my-app
          bomPath: sbom.json
